project_test/app_reserve/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_user, name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('register/', views.register, name='register'),
    path('home/', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('history/', views.history, name='history'),
    path('booking/<str:room_name>/', views.booking, name='booking'),
]

project_test/project_test/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('reserve/', include('app_reserve.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_test/app_reserve/models.py
from django.db import models
from django import forms
# Create your models here.

class AddRoom(models.Model):
    ROOM_TYPES = (
        ('Lecture', 'Lecture'),
        ('Lab', 'Lab'),
    )

    name = models.CharField(max_length=50)
    capacity = models.IntegerField()
    room_type = models.CharField(max_length=20, choices=ROOM_TYPES)
    port = models.CharField(max_length=100)
    detail = models.TextField()
    image = models.FileField(upload_to='upload', null=True, default=True)

    def __str__(self):
        return f"Room {self.name}"

class Booking(models.Model):
    room_name = models.CharField(max_length=100)
    full_name = models.CharField(max_length=100)
    email = models.EmailField()
    start_datetime = models.DateTimeField()
    end_datetime = models.DateTimeField()
    subject = models.CharField(max_length=255)
    purpose = models.TextField()

    def __str__(self):
        return f"{self.room_name} - {self.full_name} - {self.start_datetime} - {self.end_datetime}"


project_test/app_reserve/forms.py
# app_reserve/forms.py
 
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Booking

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    phone = forms.CharField(max_length=15, required=False)
 
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', 'phone')

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['room_name', 'full_name', 'email', 'start_datetime', 'end_datetime', 'subject', 'purpose']

project_test/app_reserve/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.views.decorators.csrf import csrf_protect
from .forms import CustomUserCreationForm, BookingForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from app_reserve.models import AddRoom, Booking
from django.urls import reverse
from .models import Booking

def index(request):
    return render(request, 'welcome.html')

def login_user(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invalid username or password."
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')
        
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
        else:
            error_message = "An error occurred. Please check the entered information and try again."
            return render(request, 'register.html', {'form': form, 'error_message': error_message})
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})

@login_required
def home(request):
    all_addroom = AddRoom.objects.all()
    return render(request, 'home.html',{"all_addroom":all_addroom})

@login_required
def booking(request, room_name):
    all_addroom = AddRoom.objects.all()
    if request.method == 'POST':
        form = BookingForm(request.POST)
        if form.is_valid():
            room_name = form.cleaned_data['room_name']
            start_datetime = form.cleaned_data['start_datetime']
            end_datetime = form.cleaned_data['end_datetime']
            if Booking.objects.filter(room_name=room_name, start_datetime__lte=end_datetime, end_datetime__gte=start_datetime).exists():
                return render(request, 'booking.html', {'error_message': 'This room is already booked for the selected time.'})
            form.save()
            return redirect('history')
    else:
        form = BookingForm(initial={'room_name': room_name})
    return render(request, 'booking.html', {'form': form, 'room_name': room_name, "all_addroom" :all_addroom})

@login_required
def profile(request):
    return render(request, 'profile.html')
    
@login_required
def history(request):
    all_booking = Booking.objects.all().order_by('-start_datetime')
    return render(request, 'history.html', {"all_booking": all_booking})

# Create your views here.

project_test/app_reserve/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    {% endblock %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body>
    <div class="navbar">
        <div id="mySidenav" class="sidenav">
            <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
            <a href="{% url 'home' %}">Home</a>
            <a href="{% url 'profile' %}">Profile</a>
            <a href="{% url 'history' %}">Booking History</a>
            
            {% if user.is_authenticated %}
            {% if user.is_superuser %}
                <a href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
                <a href="{% url 'logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'login' %}">Login</a>
                <a href="{% url 'register' %}">Register</a>
            {% endif %}
        </div>
        <div id="main">
            <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; {% block navbar %}{% endblock %}</span>
    
        </div>
    </div>
    {% block content %}
    {% endblock %}
<script src="{% static 'js/script.js' %}"></script>

</body>
</html>

project_test/app_reserve/templates/booking.html
{% extends "base.html" %}
{% block title %}
    <title>Booking Page</title>   
{% endblock %}
{% block navbar %}
    Booking
{% endblock %}
{% block content %}

{% if user.is_authenticated %}
<div class="book-container" style="max-width: 900px;margin: 0px auto;">


    <div class="col-30 booking-container">
        {% for addroom in all_addroom %}
            {% if addroom.name == room_name %}
                <h2 style="text-align:center">Room Details</h2>
                <div style="margin-top: 20px;">
                    <img src="{{ addroom.image.url }}" style="width:250px; height: 160px; margin: auto; display: flex; margin-bottom: 20px;">
                    <div class="profile-item">
                        <span class="profile-label">Room Name : </span>
                        <span class="profile-value">{{ addroom.name }}</span><br>
                        <span class="profile-label">Capacity : </span>
                        <span class="profile-value">{{ addroom.capacity }}</span><br>
                        <span class="profile-label">Room Type : </span>
                        <span class="profile-value">{{ addroom.room_type }}</span><br>
                        <span class="profile-label">Port : </span>
                        <span class="profile-value">{{ addroom.port }}</span><br>
                        <span class="profile-label">Detail : </span>
                        <span class="profile-value">{{ addroom.detail }}</span><br>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>


    <div class="col-70 booking-container">
        <div class="booking-header">
            <h2 style="text-transform: uppercase;">Room - {{ room_name }}</h2>
        </div>
      
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_room_name">Room name:</label>
                <input type="text" name="room_name" value="{{ room_name }}" maxlength="100" required id="id_room_name">
            </div>
        
            <div class="form-group">
                <label for="id_full_name">Name:</label>
                <input type="text" name="full_name" value="{{ user.first_name }}" maxlength="100" required id="id_full_name">
            </div>
        
            <div class="form-group">
                <label for="id_email">Email:</label>
                <input type="email" name="email" value="{{ user.email }}" maxlength="254" required id="id_email">
            </div>
        
            <div class="form-group">
                <label for="id_start_datetime">Start datetime:</label>
                <input type="datetime-local" name="start_datetime" required id="id_start_datetime">
            </div>
        
            <div class="form-group">
                <label for="id_end_datetime">End datetime:</label>
                <input type="datetime-local" name="end_datetime" required id="id_end_datetime">
            </div>
        
            <div class="form-group">
                <label for="id_subject">Subject:</label>
                <input type="text" name="subject" maxlength="255" required id="id_subject">
            </div>
        
            <div class="form-group">
                <label for="id_purpose">Purpose:</label>
                <input type="text" name="purpose" maxlength="255" required id="id_purpose">
            </div>
        
            <button type="submit">Book Room</button>
        </form>

        {% if error_message %}
            <p style="background-color: #ffe6e6;
                border: 1px solid #ff9999;
                padding: 10px;
                border-radius: 40px;
                box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.2);
                color: #ff3333;
                text-align: center;
                font-size: 16px;
                margin: 10px;
                margin-top: 0;
                ">
                {{ error_message }}</p>
        {% endif %}
    </div>

</div>
{% else %}
<p>Please login to view this page.</p>
{% endif %}

{% endblock %}

project_test/app_reserve/templates/history.html
{% extends "base.html" %}
{% block title %}
    <title>Booking History Page</title>   
{% endblock %}
{% block navbar %}
    Booking History
{% endblock %}
{% block content %}
    <div class="History-container">
        <h2 style="text-align: center;">Booking History</h2>
        <div class="search-container">
            <input type="text" id="searchInput" onkeyup="searchBooking()" placeholder="ROOM OR NAME">
        </div>
        <table id="bookingTable">
            <thead>
                <tr>
                    <th>Room</th>
                    <th>Start</th>
                    <th>End</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <!-- ข้อมูลจะถูกแทรกผ่าน JavaScript -->
            </tbody>
        </table>
        <div class="History-pagination">
            <button id="prevBtn">Back</button>
            <span id="pageNumbers"></span>
            <button id="nextBtn">Next</button>
        </div>
    </div>

<script>
    const bookingData = [
        {% for booking in all_booking %}
            { roomNumber: "{{ booking.room_name|escapejs }}", name: "{{ booking.full_name|escapejs }}", Start: "{{ booking.start_datetime }}", End: "{{ booking.end_datetime }}" },
            // { room: "{{ booking.room_name|escapejs }}", name: "{{ booking.full_name|escapejs }}", Start: "{{ booking.start_datetime }}", End: "{{ booking.end_datetime }}" },
            // { room: "{{ booking.room_name|escapejs }}", name: "{{ booking.full_name|escapejs }}", Start: "{{ booking.start_datetime }}", End: "{{ booking.end_datetime }}" },
            // { room: "{{ booking.room_name|escapejs }}", name: "{{ booking.full_name|escapejs }}", Start: "{{ booking.start_datetime }}", End: "{{ booking.end_datetime }}" },
        {% endfor %}
    ];

    const table = document.getElementById('bookingTable').getElementsByTagName('tbody')[0];
const prevBtn = document.getElementById('prevBtn');
const nextBtn = document.getElementById('nextBtn');
const pageNumbersContainer = document.getElementById('pageNumbers');
const rowsPerPage = 9;
let currentPage = 0;

function displayBookings() {
    table.innerHTML = '';
    const start = currentPage * rowsPerPage;
    const end = start + rowsPerPage;
    const bookingsToShow = bookingData.slice(start, end);

    bookingsToShow.forEach(booking => {
        const row = table.insertRow();
        row.innerHTML = `<td>${booking.roomNumber}</td>
                         <td>${booking.name}</td>
                         <td>${booking.Start}</td>
                         <td>${booking.End}</td> `;
    });
}

function generatePageNumbers() {
    const maxPage = Math.ceil(bookingData.length / rowsPerPage);
    pageNumbersContainer.innerHTML = '';
    for (let i = 0; i < maxPage; i++) {
        const pageNumber = document.createElement('span');
        pageNumber.textContent = i + 1;
        pageNumber.classList.add('pageNumber');
        pageNumber.addEventListener('click', () => {
            currentPage = i;
            displayBookings();
            updateActivePage();
        });
        pageNumbersContainer.appendChild(pageNumber);
    }
    updateActivePage();
}

function updateActivePage() {
    const pageNumbers = document.querySelectorAll('.pageNumber');
    pageNumbers.forEach((pageNumber, index) => {
        if (index === currentPage) {
            pageNumber.classList.add('Booking-active');
        } else {
            pageNumber.classList.remove('Booking-active');
        }
    });
}

function goToPrevPage() {
    if (currentPage > 0) {
        currentPage--;
        displayBookings();
        updateActivePage();
    }
}

function goToNextPage() {
    const maxPage = Math.ceil(bookingData.length / rowsPerPage);
    if (currentPage < maxPage - 1) {
        currentPage++;
        displayBookings();
        updateActivePage();
    }
}

prevBtn.addEventListener('click', goToPrevPage);
nextBtn.addEventListener('click', goToNextPage);

displayBookings();
generatePageNumbers();

function searchBooking() {
    const input = document.getElementById('searchInput').value.toLowerCase();
    const filteredBookings = bookingData.filter(booking => {
        return booking.roomNumber.toString().includes(input) || booking.name.toLowerCase().includes(input);
    });
    displayFilteredBookings(filteredBookings);
}

function displayFilteredBookings(filteredBookings) {
    const maxPage = Math.ceil(filteredBookings.length / rowsPerPage);
    pageNumbersContainer.innerHTML = '';
    for (let i = 0; i < maxPage; i++) {
        const pageNumber = document.createElement('span');
        pageNumber.textContent = i + 1;
        pageNumber.classList.add('pageNumber');
        pageNumber.addEventListener('click', () => {
            currentPage = i;
            displayFilteredBookingsPage(filteredBookings);
            updateActivePage();
        });
        pageNumbersContainer.appendChild(pageNumber);
    }
    updateActivePage();
    currentPage = 0; // Reset current page to 0
    displayFilteredBookingsPage(filteredBookings);
}

function displayFilteredBookingsPage(filteredBookings) {
    const start = currentPage * rowsPerPage;
    const end = start + rowsPerPage;
    const bookingsToShow = filteredBookings.slice(start, end);
    table.innerHTML = '';
    bookingsToShow.forEach(booking => {
        const row = table.insertRow();
        row.innerHTML = `<td>${booking.roomNumber}</td>
                         <td>${booking.name}</td>
                         <td>${booking.Start}</td>
                         <td>${booking.End}</td>`;
    });
}
</script>
    
{% endblock %}

project_test/app_reserve/templates/home.html
{% extends "base.html" %}
{% block title %}
    <title>Home Page</title>   
{% endblock %}
{% block navbar %}
    home  
{% endblock %}
{% block content %}
    <div class="Home-container">
    <div>
        <h2>Lecture</h2>
        <div class="gallery" style="display: flex;flex-wrap: wrap;">
            {% for addroom in all_addroom %}
            {% if addroom.room_type == 'Lecture' %}
            <div class="polaroid">
                <a href="{% url 'booking' room_name=addroom.name %}" style="text-decoration: none;">
                <img src="{{ addroom.image.url }}" style="width:250px; height: 160px;">
                <div class="container leftright">
                    <p>{{addroom.name}}</p>
                    <p>{{addroom.capacity}}</p>
                </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>

    <div style="padding-top: 20px;">
        <h2>Lab</h2>

        <div class="gallery" style="display: flex;flex-wrap: wrap;">
            {% for addroom in all_addroom %}
            {% if addroom.room_type == 'Lab' %}
            <div class="polaroid">
                <a href="{% url 'booking' room_name=addroom.name %}" style="text-decoration: none;">
                <img src="{{ addroom.image.url }}" style="width:250px; height: 160px;">
                <div class="container leftright">
                    <p>{{addroom.name}}</p>
                    <p>{{addroom.capacity}}</p>
                </div>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
    </div>
    </div>
{% endblock %}

project_test/app_reserve/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body class="row">
    <form method="post" action="{% url 'login' %}" class="login-container">
        {% csrf_token %}
        <h2>Login</h2>
        <input type="text" id="username" name="username" placeholder="Username" required>
        <input type="password" id="password" name="password" placeholder="Password" required>
        <button type="submit">Login</button>
        {% if error_message %}
            <p style="background-color: #ffe6e6;
            border: 1px solid #ff9999;
            padding: 10px;
            border-radius: 20px;
            box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.2);
            color: #ff3333;
            text-align: center;
            font-size: 16px;
            margin: 10px;
            margin-top: 0;
            ">
            {{ error_message }}</p>
        {% endif %}
        
        <p>Not yet a member? <a href="{% url 'register' %}">Sign Up</a></p>
    </form>

</body>
</html>

project_test/app_reserve/templates/profile.html
{% extends "base.html" %}
{% block title %}
    <title>Profile Page</title>   
{% endblock %}
{% block navbar %}
    profile
{% endblock %}
{% block content %}
    <div class="profile-container">
        <div class="profile-header">
            <h2 style="text-transform: uppercase;">Profile</h2>
            
        </div>
        <div class="profile-info" style="font-size: 20px;">
            {% if user.is_authenticated %}
            <div class="profile-item">
                <span class="profile-label">Username : </span>
                <span class="profile-value">{{ user.username }}</span>
            </div>
            <div class="profile-item">
                <span class="profile-label">First name : </span>
                <span class="profile-value">{{ user.first_name }}</span>
            </div>
            <div class="profile-item">
                <span class="profile-label">Last name : </span>
                <span class="profile-value">{{ user.last_name }}</span>
            </div>
            <div class="profile-item">
                <span class="profile-label">Email : </span>
                <span class="profile-value">{{ user.email }}</span>
            </div>
            {% else %}
                <p>Please login to view this page.</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

project_test/app_reserve/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body class="row">
    <form method="post" action="{% url 'register' %}" class="register-container">

        <h2>Register</h2>
        {% csrf_token %}
        
        <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username"  placeholder="Username">

        <input type="text" name="first_name" maxlength="30" placeholder="First Name" id="id_first_name">
        <input type="text" name="last_name" maxlength="30" placeholder="Last Name" id="id_last_name">
        <input type="email" name="email" maxlength="254" placeholder="Email" required id="id_email">

        <input type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="Password">
        <input type="password" name="password2" autocomplete="new-password" required id="id_password2" placeholder="Confirm Password">
        
        <button type="submit">Register</button>

        {% if error_message %}
            <p style="background-color: #ffe6e6;
                border: 1px solid #ff9999;
                padding: 10px;
                border-radius: 40px;
                box-shadow: 0px 0px 5px 0px rgba(0,0,0,0.2);
                color: #ff3333;
                text-align: center;
                font-size: 16px;
                margin: 10px;
                margin-top: 0;
                ">
                {{ error_message }}</p>
        {% endif %}

        <p>Already a member? <a href="{% url 'login' %}">Sign in</a></p>
    </form>

</body>
</html>

project_test/app_reserve/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Welcome Page</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<body class="row">
    <div class="welcome-container">

        <h2>Welcome</h2>
        <a href="{% url 'login' %}"><button type="submit">Login</button></a>
        <a href="{% url 'register' %}"><button type="submit">Register</button></a>

    </div>
</body>
</html>